// AUTOGENERATED by scripts/capture-analysis.mjs — 手で編集しないこと。
// fallow / knip を analysis-sample に実行した「実際の出力」を射影して保存したもの。
import type { FallowRaw, KnipRaw } from "../lib/analysis.ts";

export const analysisFixtures: {
  fallow: { raw: FallowRaw; cli: string; elapsedMs: number };
  knip: { raw: KnipRaw; cli: string; elapsedMs: number };
} = {
  "fallow": {
    "raw": {
      "check": {
        "unused_files": [
          {
            "path": "src/legacy/oldHelpers.ts"
          }
        ],
        "unused_exports": [
          {
            "path": "src/utils/format.ts",
            "export_name": "formatLegacy",
            "line": 12
          }
        ],
        "unused_dependencies": [
          {
            "package_name": "lodash",
            "line": 8
          }
        ],
        "circular_dependencies": [
          {
            "files": [
              "src/services/moduleA.ts",
              "src/services/moduleB.ts"
            ],
            "line": 1
          }
        ]
      },
      "dupes": {
        "clone_groups": [
          {
            "instances": [
              {
                "file": "src/components/Banner.tsx",
                "start_line": 3,
                "end_line": 17
              },
              {
                "file": "src/components/Card.tsx",
                "start_line": 3,
                "end_line": 17
              }
            ]
          }
        ]
      },
      "health": {
        "findings": [
          {
            "path": "src/utils/math.ts",
            "name": "computeHealthScore",
            "line": 12,
            "cyclomatic": 23,
            "cognitive": 20,
            "crap": 552,
            "severity": "critical"
          }
        ]
      },
      "elapsed_ms": 41
    },
    "cli": "── Unused Code ─────────────────────────────────────\n\n● Unused files (1)\n  src/legacy/oldHelpers.ts\n  Files not reachable from any entry point — https://docs.fallow.tools/explanations/dead-code#unused-files\n\n● Unused exports (1)\n  src/utils/format.ts\n    :12 formatLegacy\n  Exported symbols with no known consumers — https://docs.fallow.tools/explanations/dead-code#unused-exports\n\n── Dependencies ─────────────────────────────────────\n\n● Unused dependencies (1)\n  lodash\n  Listed in dependencies but never imported — https://docs.fallow.tools/explanations/dead-code#unused-dependencies\n\n── Structure ─────────────────────────────────────\n\n● Circular dependencies (1)\n  src/services/moduleA.ts\n    → moduleB.ts → moduleA.ts\n\n  Import cycles that can cause initialization failures and prevent tree-shaking — https://docs.fallow.tools/explanations/dead-code#circular-dependencies\n\n● Duplicates (1 clone groups)\n\n     15 lines  2 instances\n    src/components/Banner.tsx:3-17\n    src/components/Card.tsx:3-17\n\n  Identical code blocks detected via suffix-array analysis — https://docs.fallow.tools/explanations/duplication#clone-groups\n\n■ Metrics: 188 LOC · dead files 11.1% · dead exports 8.3% · avg cyclomatic 2.6 · p90 cyclomatic 4 · maintainability 92.1 (good) · 0 churn hotspots · 1 circular dep · 1 unused dep\n\n● High complexity functions (1)\n  src/utils/math.ts\n    :12 computeHealthScore CRITICAL\n          23 cyclomatic   20 cognitive   42 lines\n         552.0 CRAP\n  Functions exceeding cyclomatic, cognitive, or CRAP thresholds (https://docs.fallow.tools/explanations/health#complexity-metrics)",
    "elapsedMs": 645
  },
  "knip": {
    "raw": {
      "issues": [
        {
          "file": "src/legacy/oldHelpers.ts",
          "files": [
            {
              "name": "src/legacy/oldHelpers.ts"
            }
          ],
          "exports": [],
          "types": [],
          "dependencies": [],
          "devDependencies": [],
          "duplicates": []
        },
        {
          "file": "package.json",
          "files": [],
          "exports": [],
          "types": [],
          "dependencies": [
            {
              "name": "lodash",
              "line": 8
            }
          ],
          "devDependencies": [],
          "duplicates": []
        },
        {
          "file": "src/utils/format.ts",
          "files": [],
          "exports": [
            {
              "name": "formatLegacy",
              "line": 12
            }
          ],
          "types": [],
          "dependencies": [],
          "devDependencies": [],
          "duplicates": []
        }
      ]
    },
    "cli": "Unused files (1)\nsrc/legacy/oldHelpers.ts\nUnused dependencies (1)\nlodash  package.json:8:6\nUnused exports (1)\nformatLegacy  function  src/utils/format.ts:12:17",
    "elapsedMs": 592
  }
};
