// AUTOGENERATED by scripts/capture-analysis.mjs — 手で編集しないこと。
// analysis-sample/ の中身（= 解析対象そのもの）を表示用に取り込んだもの。
export type SampleLang = "ts" | "tsx" | "json";
export type SampleFile = { path: string; lang: SampleLang; code: string };

export const sampleFiles: SampleFile[] = [
  {
    "path": "src/index.ts",
    "lang": "ts",
    "code": "import { renderDashboard } from \"./App\";\nimport { computeHealthScore } from \"./utils/math\";\nimport { formatCurrency } from \"./utils/format\";\nimport { startSync } from \"./services/moduleA\";\nimport { Card } from \"./components/Card\";\nimport { Banner } from \"./components/Banner\";\n\nconst score = computeHealthScore({\n  coverage: 82,\n  complexity: 14,\n  duplication: 3,\n  churn: 27,\n  dependencies: 48,\n  openIssues: 5,\n});\n\nrenderDashboard({\n  title: \"Project Health\",\n  subtitle: formatCurrency(score * 1000),\n  widgets: [Card, Banner],\n});\n\nstartSync();\n"
  },
  {
    "path": "src/App.tsx",
    "lang": "tsx",
    "code": "import { createElement, type ReactElement } from \"react\";\n\ntype DashboardProps = {\n  title: string;\n  subtitle: string;\n  widgets: Array<() => ReactElement>;\n};\n\nexport function renderDashboard(props: DashboardProps): ReactElement {\n  return createElement(\n    \"section\",\n    { className: \"dashboard\" },\n    createElement(\"h1\", null, props.title),\n    createElement(\"p\", { className: \"subtitle\" }, props.subtitle),\n    ...props.widgets.map((Widget) => createElement(Widget)),\n  );\n}\n"
  },
  {
    "path": "src/utils/format.ts",
    "lang": "ts",
    "code": "const JPY = new Intl.NumberFormat(\"ja-JP\", {\n  style: \"currency\",\n  currency: \"JPY\",\n});\n\nexport function formatCurrency(value: number): string {\n  return JPY.format(Math.round(value));\n}\n\n// index.ts からは formatCurrency しか使われていないため、これは未使用 export。\n// knip も fallow も「未使用 export」として検出する。\nexport function formatLegacy(value: number): string {\n  return `¥${value.toFixed(0)}`;\n}\n"
  },
  {
    "path": "src/utils/math.ts",
    "lang": "ts",
    "code": "export type Metrics = {\n  coverage: number;\n  complexity: number;\n  duplication: number;\n  churn: number;\n  dependencies: number;\n  openIssues: number;\n};\n\n// 意図的に分岐の多い関数。循環的複雑度・認知的複雑度が高く、\n// fallow は「複雑度ホットスポット」として検出する（knip は対象外）。\nexport function computeHealthScore(m: Metrics): number {\n  let score = 100;\n\n  if (m.coverage < 50) score -= 30;\n  else if (m.coverage < 70) score -= 18;\n  else if (m.coverage < 85) score -= 8;\n  else if (m.coverage < 95) score -= 2;\n\n  if (m.complexity > 30) score -= 25;\n  else if (m.complexity > 20) score -= 15;\n  else if (m.complexity > 12) score -= 8;\n  else if (m.complexity > 6) score -= 3;\n\n  if (m.duplication > 10) score -= 20;\n  else if (m.duplication > 5) score -= 10;\n  else if (m.duplication > 2) score -= 4;\n\n  if (m.churn > 50) score -= 12;\n  else if (m.churn > 25) score -= 6;\n\n  switch (true) {\n    case m.dependencies > 80:\n      score -= 10;\n      break;\n    case m.dependencies > 50:\n      score -= 5;\n      break;\n    case m.dependencies > 30:\n      score -= 2;\n      break;\n    default:\n      break;\n  }\n\n  if (m.openIssues > 20 && m.churn > 30) score -= 8;\n  else if (m.openIssues > 10) score -= 4;\n  else if (m.openIssues > 5) score -= 2;\n\n  if (score < 0) score = 0;\n  if (score > 100) score = 100;\n  return score / 100;\n}\n"
  },
  {
    "path": "src/components/Card.tsx",
    "lang": "tsx",
    "code": "import { createElement, type ReactElement } from \"react\";\n\nexport function Card(): ReactElement {\n  // --- 重複ブロック（Banner.tsx と完全に同一）-------------------\n  const items = [\"coverage\", \"complexity\", \"duplication\", \"churn\"];\n  const rows = items.map((key) => {\n    const label = key.charAt(0).toUpperCase() + key.slice(1);\n    const status = key === \"duplication\" ? \"warn\" : \"ok\";\n    const icon = status === \"ok\" ? \"✓\" : \"!\";\n    const weight = key.length * 2 + (status === \"ok\" ? 1 : 0);\n    return { key, label, status, icon, weight };\n  });\n  const summary = rows.filter((r) => r.status === \"ok\").length;\n  const total = rows.reduce((acc, r) => acc + r.weight, 0);\n  // --- 重複ブロックここまで -------------------------------------\n\n  return createElement(\n    \"div\",\n    { className: \"card\" },\n    createElement(\"h2\", null, \"Card\"),\n    createElement(\"span\", null, `${summary}/${rows.length} ok · w${total}`),\n  );\n}\n"
  },
  {
    "path": "src/components/Banner.tsx",
    "lang": "tsx",
    "code": "import { createElement, type ReactElement } from \"react\";\n\nexport function Banner(): ReactElement {\n  // --- 重複ブロック（Card.tsx と完全に同一）-------------------\n  const items = [\"coverage\", \"complexity\", \"duplication\", \"churn\"];\n  const rows = items.map((key) => {\n    const label = key.charAt(0).toUpperCase() + key.slice(1);\n    const status = key === \"duplication\" ? \"warn\" : \"ok\";\n    const icon = status === \"ok\" ? \"✓\" : \"!\";\n    const weight = key.length * 2 + (status === \"ok\" ? 1 : 0);\n    return { key, label, status, icon, weight };\n  });\n  const summary = rows.filter((r) => r.status === \"ok\").length;\n  const total = rows.reduce((acc, r) => acc + r.weight, 0);\n  // --- 重複ブロックここまで -------------------------------------\n\n  return createElement(\n    \"header\",\n    { className: \"banner\" },\n    createElement(\"strong\", null, \"Banner\"),\n    createElement(\"span\", null, `${summary}/${rows.length} ok · w${total}`),\n  );\n}\n"
  },
  {
    "path": "src/services/moduleA.ts",
    "lang": "ts",
    "code": "import { syncB } from \"./moduleB\";\n\n// moduleA → moduleB → moduleA の循環依存。\n// fallow は循環依存として検出する（knip は対象外）。\nexport function startSync(): string {\n  return `A:${syncB()}`;\n}\n\nexport function helperA(): string {\n  return \"helper-a\";\n}\n"
  },
  {
    "path": "src/services/moduleB.ts",
    "lang": "ts",
    "code": "import { helperA } from \"./moduleA\";\n\nexport function syncB(): string {\n  return `B:${helperA()}`;\n}\n"
  },
  {
    "path": "src/legacy/oldHelpers.ts",
    "lang": "ts",
    "code": "// このファイルはどこからも import されていない（未使用ファイル）。\n// knip も fallow も「未使用ファイル」として検出する。\n\nexport function deprecatedSlugify(input: string): string {\n  return input.toLowerCase().replace(/\\s+/g, \"-\");\n}\n\nexport function deprecatedTruncate(input: string, max: number): string {\n  return input.length > max ? `${input.slice(0, max)}…` : input;\n}\n"
  },
  {
    "path": "package.json",
    "lang": "json",
    "code": "{\n  \"name\": \"dashboard-sample\",\n  \"private\": true,\n  \"version\": \"1.0.0\",\n  \"type\": \"module\",\n  \"description\": \"解析デモ用サンプル。両ツールの検出差が出るよう意図的に問題を仕込んである。\",\n  \"dependencies\": {\n    \"lodash\": \"^4.17.21\",\n    \"react\": \"^19.0.0\"\n  },\n  \"devDependencies\": {\n    \"@types/react\": \"^19.0.0\"\n  }\n}\n"
  }
];
